from .testrunnerplugin import testrunner_plugin


# new
from .clingo_main_plugin import clingo_main_plugin
from .source_plugin import source_plugin
from .clingo_control_plugin import clingo_control_plugin
from .clingo_syntaxerror_plugin import clingo_syntaxerror_plugin
from .clingo_sequencer_plugin import clingo_sequencer_plugin
from .clingo_defaults_plugin import clingo_defaults_plugin